[build]
  command = "pip install -r requirements.txt && echo 'Build completed'"
  functions = "functions"
  publish = "."

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "python app.py"
  port = 5000
  publish = "."

